version: '3'

services:
  portainer:
    restart: always
    image: portainer/portainer:latest
    container_name: portainer
    volumes:
      - ./data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    dns:
      - 1.1.1.1
      - 1.0.0.1
    networks:
      dev:
        ipv4_address: 10.10.10.253

  dns:
    restart: always
    image: jherrerotardon/dnsmasq:2.80
    container_name: dns
    volumes:
      - ./files/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    ports: 
      - 53:53
    networks:
      dev:
        ipv4_address: 10.10.10.2

  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    depends_on: 
      - dns
    volumes:
      - ~/ProjectsPersonal/php:/var/www:cached
      - ./files/nginx/config/conf.d:/etc/nginx/conf.d:cached
      - ./files/nginx/certs:/etc/ssl/certs:cached
      - ./logs/nginx:/var/log/nginx
    dns:
      - 10.10.10.2
    ports:
      - 80:80
      - 443:443
    networks:
      dev:
        ipv4_address: 10.10.10.3
        
  redis:
    restart: always
    container_name: redis
    image: "redis:latest"
    depends_on: 
      - dns
    volumes: 
      - ./logs/redis:/var/log/redis
      - ./data/redis:/var/lib/redis
    dns:
      - 10.10.10.2
    networks:
      dev:
        ipv4_address: 10.10.10.20
  
  mongodb:
    image: mongo:4.2
    container_name: mongodb
    depends_on: 
      - dns
    volumes:
      - ./logs/mongodb:/var/log/mongodb
      - ./data/mongodb:/data/db
    dns:
      - 10.10.10.2
    networks:
      dev:
        ipv4_address: 10.10.10.21

  mysql:
    image: mysql:8
    container_name: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: development
    depends_on: 
      - dns
    volumes:
      - ./logs/mysql:/var/log/mysql
      - ./data/mysql:/var/lib/mysql
    dns:
      - 10.10.10.2
    ports: 
      - 3306:3306
    networks:
      dev:
        ipv4_address: 10.10.10.22

  php:
    image: jherrerotardon/php:7.4-fpm
    container_name: php
    depends_on: 
      - dns
    volumes:
      - ~/Projects/php:/var/www:cached
      - ./files/php/config/:/usr/local/etc/:cached
      - ./logs/php:/var/log/php:cached
    dns:
      - 10.10.10.2
    ports: 
      - 9000:9000
    networks:
      dev:
        ipv4_address: 10.10.10.23

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    depends_on:
      - dns
    volumes: 
      - ./logs/rabbitmq:/var/log/rabbitmq
      - ./data/rabbitmq:/var/lib/rabbitmq
    dns: 
      - 10.10.10.2
    networks:
      dev:
        ipv4_address: 10.10.10.24

networks:
  dev:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
